USE [CadastroCurriculos];
GO

IF OBJECT_ID(N'dbo.Candidatos', N'U') IS NULL
BEGIN
    THROW 50001, 'A tabela dbo.Candidatos nao foi encontrada.', 1;
END;

SELECT TABLE_SCHEMA, TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = N'dbo' AND TABLE_NAME = N'Candidatos';

SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, IS_NULLABLE, COLUMN_DEFAULT
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = N'dbo' AND TABLE_NAME = N'Candidatos'
ORDER BY ORDINAL_POSITION;

SELECT @@VERSION AS Versao;
GO
